# Generated by Django 2.2.7 on 2021-07-14 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='English_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='English_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='English_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='English_Half_Yearly_Exam_term2'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Hindi_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Hindi_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Hindi_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Hindi_Half_Yearly_Exam_term2'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Marathi_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Marathi_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Marathi_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Marathi_Half_Yearly_Exam_term2'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Math_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Math_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Math_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Math_Half_Yearly_Exam_term2'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Sci_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Sci_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Sci_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Sci_Half_Yearly_Exam_term2'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='So_Sci_Half_Yearly_Exam_term1',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='So_Sci_Half_Yearly_Exam_term1'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='So_Sci_Half_Yearly_Exam_term2',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='So_Sci_Half_Yearly_Exam_term2'),
        ),
    ]
